from faker import Faker
import random

fake = Faker()

def generate_document(progress_id):
    """
    Customize your test document structure here.
    """
    return {
        # By default, _id is automatically generated by MongoDB
        "progress_id": progress_id,
        "name": fake.name(),
        "email": fake.email(),
        "address": fake.address().replace("\n", ", "),
        "phone": fake.phone_number(),
        "company": fake.company(),
        "created_at": fake.iso8601(),
        "status": random.choice(["active", "inactive", "pending"]),
        "value": random.randint(1, 1000000)
    }
